/*
 * Burpee Counter
 *
 * The Burpee Counter API
 *
 * API version: 1.0.0
 * Contact: burpee-counter@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package main

import (
	"github.com/gorilla/handlers"
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "asi-tech/burpee-counter-api/go"
)

func main() {
	log.Printf("Server started")

	router := sw.NewRouter()
	log.Fatal(http.ListenAndServe(":3010", handlers.CORS(handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type", "Authorization"}), handlers.AllowedMethods([]string{"GET", "POST", "PUT", "HEAD", "OPTIONS"}), handlers.AllowedOrigins([]string{"*"}))(router)))

	//log.Fatal(http.ListenAndServe(":3010", router))
}
